filebrowser/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    
    # filebrowser urls
    url(r'^browse/$', 'filebrowser.views.browse', name="fb_browse"),
    url(r'^mkdir/', 'filebrowser.views.mkdir', name="fb_mkdir"),
    url(r'^upload/', 'filebrowser.views.upload', name="fb_upload"),
    url(r'^rename/$', 'filebrowser.views.rename', name="fb_rename"),
    url(r'^delete/$', 'filebrowser.views.delete', name="fb_delete"),
    url(r'^versions/$', 'filebrowser.views.versions', name="fb_versions"),
    
    url(r'^check_file/$', 'filebrowser.views._check_file', name="fb_check"),
    url(r'^upload_file/$', 'filebrowser.views._upload_file', name="fb_do_upload"),
    
)

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib.auth import views as auth_views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/filebrowser/', include('filebrowser.urls')),
	url(r'^tinymce/', include('tinymce.urls')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^admin_tools/', include('admin_tools.urls')),
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	
	url(r'^captcha/', include('captcha.urls')),
	
	url(r'^', include('subject_user.urls')),
	url(r'^configuration', include('configuration.urls')),
	
	url(r'^mformulas/', include('mformulas.urls')),
	url(r'^video/', include('videoplayer.urls')),
	url(r'^training/', include('training.urls')),
	url(r'^onlineuser/', include('onlineuser.urls')),
	url(r'^actions/', include('news.urls')),
	url(r'^activity/invitefriend/', include('invitefriend.urls')),
	url(r'^', include('statistics.urls')),
	
	url(r'^register/$', 'project.views.register'),
	url(r'^register/order/(?P<user_id>[0-9]+)/$', 'project.views.order', {'type':0, 'template':'robokassa/order.html'}),
	url(r'^accounts/prolong/$', 'project.views.order', {'type':1, 'template':'robokassa/prolong.html'}),
	url(r'^accounts/analysis/$', 'project.views.order', {'type':2, 'template':'robokassa/analysis.html'}),
	url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='auth_logout'),
	url(r'^accounts/login/$', auth_views.login),
	url(r'^password/reset/$', 'django.contrib.auth.views.password_reset', {'template_name':'registration/password_reset_form1.html',} ),
	url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', {'template_name':'registration/password_reset_done1.html',} ),
	url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name':'registration/password_reset_confirm1.html',} ),
	url(r'^password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete', {'template_name':'registration/password_reset_complete1.html',} ),
	url(r'^', include('registration.urls')),
	
	url(r'^robokassa/', include('robokassa.urls')),
)

subject/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from tinymce import models as TinymceField
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import datetime
import re
import os

from pytils.translit import slugify

from mformulas.helper import TextToMFormula, search_mformulas

#######################################################################################################################
#######################################################################################################################

#Предмет
class Subject(models.Model):
	title = models.CharField(max_length=500, verbose_name=_("title"))
	slug = models.SlugField(unique=True, verbose_name=_("slug"))
	text = TinymceField.HTMLField(max_length=10000, verbose_name=_("text"), blank=True, help_text=_("This text about a subject isn't displayed anywhere"))
	is_olympiad = models.BooleanField(verbose_name=_("is olympiad"), default=False)
	is_active = models.BooleanField(verbose_name=_("is active"), default=True)
	sort = models.IntegerField(verbose_name=_("sort"), default=0)
	
	def __unicode__(self):
		return u'%s' % self.title
	
	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Subject, self).save(*args, **kwargs)	
	
	def get_absolute_url(self):
		return '/subjects/subject/%s/' % self.slug
		
	def get_lesson_list(self):
		return self.subjects_lesson.filter(is_active=True)
		
	def get_use_list(self):
		return self.subjects_use.filter(is_active=True)
	
	def get_offset_list(self):
		return self.subjects_offset.filter(is_active=True)
	
	class Meta: 
		verbose_name = _("subject")
		verbose_name_plural = _("subjects")
		ordering = ['sort', 'id']
		
#######################################################################################################################
#######################################################################################################################

#Задача
class Task(models.Model):
	title = models.CharField(max_length=1000, verbose_name=_("title"))
	slug = models.SlugField(unique=True,max_length=1000, verbose_name=_("slug"))
	text_task = TinymceField.HTMLField(max_length=10000, verbose_name=_("text task"))
	is_active = models.BooleanField(verbose_name=_("is active"), default=True)
	sort = models.IntegerField(verbose_name=_("sort"), default=0)
	
	def __unicode__(self):
		return u'%s' % self.title
		
	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Task, self).save(*args, **kwargs)
		#search_mformulas(models=[Task])
		
	def get_absolute_url(self):
		return '/subjects/task/%s/' % self.slug
	
	#Возвращает ответы
	def get_version_answer(self):
		return self.version_answer.filter(is_active=True)
		
	#Проверяет верный ли ответ
	def is_true_answer(self, query_string):
		k, loop = 0, 0
		va = self.get_version_answer().filter(task=self, is_correctly=True)

		r = re.compile('(answer_([0-9]+))=(.+?)\&')
		iterator = r.findall(u'&' + query_string + u'&')

		for match in iterator:
			key, id, value = match[0], match[1], match[2]

			if va[0].type_answer == 'text':
				if (va.filter(answer=value)): k += 1
			else:
				if (va.filter(answer=value)) or (va.filter(id=id)): k += 1
			loop += 1

		if k == va.count() and k == loop: return True
		return False
		
	#Создает html форму с ответами пользователя
	def users_answer_form(self, query_string='next=1&answerr=1&subject_name=matematika&answer=3',idisabled='disabled'):
		va = self.get_version_answer()
		r = re.compile('(answer_([0-9]+))=(.+?)\&')
		iterator = r.findall(u'&' + query_string + u'&')
		html = ''
		
		for v in va:
			ichecked = ''
			iname = 'answer_%s'%v.id
			ivalue = ''
			ilabel = ''
			value = ''
			for match in iterator:
				key, id, value = match[0], match[1], match[2]
				if int(id)>0:
					if v.id == int(id) and v.type_answer == 'radio':
						ichecked = 'checked'
						iname = 'answer'
						value = VersionAnswer.objects.filter(id=id)[0].answer

					elif id and v.id == int(id):
						if v.type_answer == 'checkbox':
							ichecked = 'checked'
				if v.type_answer == 'text':
					iname = 'answer_0'
				if v.type_answer == 'radio':
					iname = 'answer'

			if v.type_answer == 'checkbox':
				ilabel = "<label class='f_left' for='answer_%(id)d' tabindex='%(id)d'>%(answer)s</label>" % {'id':v.id, 'answer':v.answer}
			if v.type_answer == 'radio':
				ilabel = "<label class='f_left' for='answer_%(id)d' tabindex='%(id)d'>%(answer)s</label>" % {'id':v.id, 'answer':v.answer}
				
			html += "<tr><td><input class='f_left' id='answer_%s' type='%s' name='%s' value='%s' %s %s /></td><td>%s<div class='clr'></div></td></tr>" % (
				v.id, v.type_answer, iname, value, ichecked, idisabled, ilabel
			)
		return html
	users_answer_form.allow_tags = True
	
	def get_admin_version_answer(self):
		s = u''
		for answer in VersionAnswer.objects.filter(task=self, is_active=True).order_by('sort'):
			if answer.is_correctly: 
				checked =u'checked'
				color=u'1px blue solid'
			else: 
				checked =u''
				color=u'none'
			s += u"<tr><td style='border:none' width='20px'><input style='border:%s' type='%s' %s disabled value='%s'></td><td style='border:none'>%s</td></tr>" % (color,answer.type_answer, checked, answer.answer, TextToMFormula(answer.answer))
		return u'<table >%s</table>' % s
	get_admin_version_answer.short_description = _("Get answer")
	get_admin_version_answer.allow_tags = True
	
	def get_admin_text_task(self):
		return TextToMFormula(self.text_task)
	get_admin_text_task.short_description = _("Get test task")
	get_admin_text_task.allow_tags = True
		
	class Meta: 
		verbose_name = _("task") 
		verbose_name_plural = _("tasks") 
		ordering = ['sort']
		
#######################################################################################################################
#######################################################################################################################
		
#Варианты ответа
class VersionAnswer(models.Model):
	answer = TinymceField.HTMLField(max_length=1000, verbose_name=_("answer"))
	task = models.ForeignKey(Task, verbose_name=_("task"),related_name=u'version_answer')
	TYPE_CHOICES = ( 
		('checkbox',_("checkbox")),
		('radio',_("radio")),
		('text',_("text")),
	) 
	type_answer=models.CharField(max_length=100, choices=TYPE_CHOICES,verbose_name=_("type answer")) 
	
	is_correctly = models.BooleanField(verbose_name=_("is correctly"), default=False)
	is_active = models.BooleanField(verbose_name=_("is active"), default=True)
	sort = models.IntegerField(verbose_name=_("sort"), default=0)
	
	def save(self, *args, **kwargs):
		super(VersionAnswer, self).save(*args, **kwargs)
		if self.is_correctly == True and self.type_answer == 'radio':
			VersionAnswer.objects.filter(task=self.task).exclude(id=self.id).update(is_correctly=False)
		if self.type_answer:
			VersionAnswer.objects.filter(task=self.task).update(type_answer=self.type_answer)
			
		#search_mformulas(models=[VersionAnswer])

	def __unicode__(self):
		return '%s' % self.answer 
		
	class Meta: 
		verbose_name = _("version answer") 
		verbose_name_plural = _("versions answers")
		ordering = ['sort', 'id']

#Сложность
class Complexity(models.Model):
	title = models.CharField(max_length=500, verbose_name=_("title"))
	is_active = models.BooleanField(verbose_name=_("is active"), default=True)
	sort = models.IntegerField(verbose_name=_("sort"), default=0)
	
	def __unicode__(self):
		return '%s' % self.title
	
	class Meta: 
		verbose_name = _("complexity") 
		verbose_name_plural = _("complexitys")
		ordering = ['sort', 'id']
		
#######################################################################################################################
#######################################################################################################################
		
#Урок
class Lesson(models.Model):
	title = models.CharField(max_length=500, verbose_name=_("title"))
	slug = models.SlugField(unique=True, verbose_name=_("slug"))
	text = TinymceField.HTMLField(max_length=10000, verbose_name=_("text"), blank=True)
	subject = models.ForeignKey(Subject, verbose_name=_("subject"),related_name=u'subjects_lesson')
	date = models.DateField(verbose_name=_("date lesson"), default=datetime.datetime.now())
	teacher = models.ForeignKey(User, verbose_name=_("teacher"))
	level = models.IntegerField(verbose_name=_("class"),)
	complexity = models.ForeignKey(Complexity, verbose_name=_("complexity"))
	video = models.FileField(max_length=100, upload_to=u'upload/lesson/video/', verbose_name=_("video"), blank=True, null=True)
	tasks = models.ManyToManyField(Task, verbose_name=_("tasks"), through='Lesson_Task')
	
	is_active = models.BooleanField(verbose_name=_("is active"), default=True)
	sort = models.IntegerField(verbose_name=_("sort"), default=0)
	
	def __unicode__(self):
		return u'%s' % self.title
	
	def clean(self):
		r = re.compile('^([a-zA-Z0-9_-]+)\.(flv)$')
		if self.video:
			if not r.findall(os.path.split(self.video.url)[1]):
				raise ValidationError(_("File_name_validation_error"))
	
	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Lesson, self).save(*args, **kwargs)
		search_mformulas(models=[Lesson])
		
	def get_absolute_url(self):
		return '/subjects/lesson/%s/?subject_name=%s' % (self.slug,self.subject.slug)
		
	def get_absolute_olympiad_url(self):
		return '/olympiad/lesson/%s/?subject_name=%s' % (self.slug,self.subject.slug)
		
	#Кол-во просмотров урока
	def get_number_of_viewings(self):
		return self.userlesson_set.all().count()
	get_number_of_viewings.short_description = _("number of viewings")
		
	def get_task_list(self):
		return self.tasks.filter(is_active=True)
	
	def get_task_list_admin(self):
		s = u''
		for item in self.tasks.filter(is_active=True).order_by('sort'):
			s += u'<div>%s</div>' % (item)
		return u'%s' % s
	get_task_list_admin.short_description = _("get_task_list_admin")

subject/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _

#######################################################################################################################
#######################################################################################################################

#Форма поиска урока
class SearchForm(forms.Form):
	title = forms.CharField(max_length=100, label=_("Theme"), required=False)
	date = forms.DateField(label=_("Date"), required=False)
	
#######################################################################################################################
#######################################################################################################################

subject/templates/lesson/dictionary_block.html
{% if formulas %}
	<ul>
		{% for formula in formulas %}
			<li>
				<div class="title_li"><h4>{{ formula.formula.title }}</h4></div>
				<div class="formula">{{ formula.formula.get_formula }}<span class="close">&nbsp;</span></div>
			</li>
		{% endfor %}
		<script>
			$('.right_block ul li .title_li').click(
				function(){
					$(this).parent().addClass('hover_formula');
					MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
			});
			$('.right_block .close').click(
				function(){
					$(this).parents('.hover_formula').removeClass('hover_formula');
				});
		</script>
	</ul>
{% else %}
	Формул из этого урока в словаре нет.
{% endif %}

subject/templates/lesson/lesson.html
{% extends "index.html" %}
{% load subject_user_tags %}

{% block title %}Уроки{% endblock %}
{% block title_page %}Изучайте уроки. Выполняйте практические задания.{% endblock%}
{% block block_content_top %}Выберете подходящий урок из списка{% endblock%}
{% block script%}
	<script type="text/javascript">
		$(function() {
			$d3 =$('.scroll_big').jScrollPane({autoReinitialise: true});
			$( "#id_date" ).datepicker($.datepicker.regional["ru"]);
		});
	</script>
{% endblock %}

{% block content %}
	<div class="text-block radius6 col1 ">
		<div class="block-inner radius4">
			<div class="scroll_big">
				<div class="block-front">
					<div id="training_list" class="offset">
						{% block content_text %}
							{% if obj_list %}
								<form id="statistik_form" name="search_form" action="" method="post" class="search task">{% csrf_token %}
									{{ form.title }}
									{{ form.date }}
									<input type="submit" class="but f_right" name="submit_search_form" value="Поиск" onclick="change_search_form()">
								</form>
								<script>
									function change_search_form(){
										if(document.search_form.title.value == "Тема") document.search_form.title.value = "";
										if(document.search_form.date.value == "Дата") document.search_form.date.value = "";
									}
								</script>
								<table id="table_list" width='705px' class="otstup_bottom">
									<tr>
										<th class="th_first" width="10px"></th>
										<th  width="370px">Тема урока</th>
										<th  width="200px">Преподаватель</th>
										<th  width="70px">Дата</th>
										<th  width="50px">Сложность</th>
										<th  width="23px">%</th>
										<th class="th_last" width="10px"></th>
									</tr>
									{% block table %}
										{% for item in obj_list %}
											<tr {% if forloop.last %}class="tr_last"{% endif %}>
												<td {% ifequal item|is_mastered:request.user_anonymous 'is_master'%}class="ok td_first" title="Освоено"{% else %}{% ifequal item|is_mastered:request.user_anonymous 'is_development'%}class="na_osvoenii td_first" title="На освоении" {% else %}class="td_first"{% endifequal %}{% endifequal %} ></td>
												<td class="cursor_p">
													<a href="{{ item.get_absolute_url }}">
														{{ item.title }}
													</a>
												</td>
												<td>{{ item.teacher.get_full_name }}</td>
												<td>{{ item.date|date:"j N" }}</td>
												<td>{{ item.complexity }}</td>
												<td>{{ item|get_percent:auser }}</td>
												<td class="td_last" width="10px"></td>
											</tr>
										{% endfor %}
									{% endblock%}
								</table>
								{% include "paginate.html" %}
							{% else %}
								Список уроков пуст.
							{% endif %}
						{% endblock%}
					</div>
				<div class="clr"></div>
				</div>
			</div>
		</div>
	</div>
{% endblock%}

subject/templates/lesson/lesson_item.html
{% extends "lesson/lesson.html" %}
{% load mformulas_tags dictionary_tags %}

{% block block_content_top %}{{ l.title }}{% endblock%}

{% block script %}
	
	<script type="text/javascript">
		$(function(){
			$d1 = $("#d1").jScrollPane({autoReinitialise: true});
			$d2 = $("#d2").jScrollPane({autoReinitialise: true});
			$d3 = $d1;
			$('#d1').bind('jsp-scroll-y', function(event, scrollPositionY) {
				$d2.data('jsp').scrollToY(scrollPositionY);
			});
		});
	</script>
{% endblock %}

{% block content %}
	{% load subject_user_tags %}
	<div class="right_block text-block radius6 col2">
		<div id="hid">
			<div class="block-inner radius4" id="d2" >
				<div id="mydictionary" style="z-index: 1000;" class="block-front">
					{% block right_menu %}
						{% MFormulasDictionary dictionary_data 'lesson/dictionary_block.html' %}
					{% endblock%}
					<div class="clr"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="text-block radius6 col2">
        <div class="block-inner radius4">
			<a class="add_bookmark" href="/subjects/lesson/bookmark/{{ l.id }}/" title="В закладки"><span class="sprite">В закладки</span></a>
			<div class="scroll" id="d1" >
				<div class="block-front">
					{% block center %}
						
						{% if l.video %}
							<div class="block_video">
								<iframe src="/video/{{ l.id }}/{{ l.video.url }}/?subject_name={{ subject_name }}" width="512" height="333" align="left" frameborder="no">
									Ошибка! Видео файл недоступен.
								</iframe>
							</div>
						{% endif %}
						
						<div class="text-lesson">{{ l.text|safe|MFormula|MFLinjSubject:subject_name }}</div>
						<div class="clr"></div>
						{% if l.get_task_list %}
							<h2>Cписок задач:</h2>
							<ul class="list">
								{% for item in l.get_task_list %}
									<li class="clr mbottomb">
										<div>
											<span id="answer_res_{{ item.id }}" style="float:right;color:green"></span>
											<h4 {% TaskLessonUserFound l item %}>{{ item.title }}</h4>
											
											<div class="task_offset">
												<h5>{{ item.text_task|safe|MFormula|MFLinjSubject:subject_name }}</h5>
												<form id="form_{{  item.id }}" style="text-align:center" class="task" action="" method="get">
													<input type="hidden" name="subject_name" value="{{ subject_name }}">
													<input type="hidden" name="lesson_id" value="{{ l.id }}">
													<input type="hidden" name="task_id" value="{{ item.id }}">
													<table>
														{% for answer in item.get_version_answer %}
															<tr>
																<td {% ifequal item1.type_answer 'checkbox' %}width="0px"{% else %}width="30px"{% endifequal %}>
																	<input class="f_left" id="answer_{{ answer.id }}" type="{{ answer.type_answer }}" {% ifequal answer.type_answer 'radio' %} name="answer" {% else %} {% ifequal answer.type_answer 'text' %} name="answer_0" {% else %}name="answer_{{ answer.id }}"{% endifequal %} {% endifequal %} {% ifequal answer.type_answer 'text' %}>{% else %}value="{{ answer.answer }}">{% endifequal %}
																</td>
																<td>
																	{% ifnotequal answer.type_answer 'text' %}
																		<label class="f_left" for="answer_{{ answer.id }}" tabindex="{{ answer.id }}">
																			{{ answer.answer|safe|MFormula|MFLinjSubject:subject_name }}
																		</label>
																		<div class="clr"></div>
																	{% endifnotequal %}
																</td>
															</tr>
														{% endfor %}
													</table>
													<div class="clr"></div>
													
													<input type="submit" class="but scroll-to-element-demo f_right" value="Ответить">
													{% if l|get_text_solution:item %}
														{% if item|buy_task:request.user_anonymous %}
															<div class="clr"></div>
															<div class="buy radius4 otstup_top">
																<h2>Решение:</h2>
																<div class="otstup_top">
																	{{ l|get_text_solution:item|safe|MFormula|MFLinjSubject:subject_name }}
																</div>
															</div>
														{% else %}
															<a class="but scroll-to-element-demo f_right otstup_right" style="width:130px" href="/accounts/analysis/?lesson={{ l.id }}&task={{ item.id }}&back={{ request.META.HTTP_REFERER }}">Купить решение</a>
														{% endif %}
													{% endif %}
												</form>
												<div class="clr"></div>
											</div>
										</div>
									</li>
								{% endfor %}
								<div class="clr"></div>
							</ul>
						{% endif %}
						<div class="clr"></div>
						<a class="but otstup_top" style="width:130px; margin-left:180px;float:left;" href="/subjects/lesson/?subject_name={{subject_name}}">Завершить урок</a>
					{% endblock%}
					<div class="clr"></div>
				</div>
			</div>
        </div>
    </div>


	<div class="clr"></div>
	
	<script>

		$(function(){
			$('form.task').submit(function(){
				var task_id = this.elements["task_id"].value;
				var form_id = $(this).attr('id');
				var dataform = $(this).serialize();
				input = $('#'+form_id+' input:radio[name=answer]:checked');
				if (input.attr('id')!=undefined)
				{
					a = input.attr('id');
					val =input.val();
					dataform=dataform+'&'+a+'='+val;
					};
				$.ajax({
					type: "GET",
					url: "/subjects/lesson/task/results/",
					data: dataform,
					error: function(){},
					success: function(data){
						if (data == '1') {
							$("#answer_res_" + task_id).html('&nbsp;Верно!');
							$("#answer_res_" + task_id).next().addClass('ok');
							$("#answer_res_" + task_id).css('color','green');
						} else {
							$("#answer_res_" + task_id).html('&nbsp;Не верно!');
							$("#answer_res_" + task_id).css('color','red');
						};
					}
				});
				return false;
			});
			
			$('a.mformulas_link').click(function(){
				$.ajax({
					type: "GET",
					url: $(this).attr("href"),
					success: function(data){
						$("#mydictionary").load("/mformulas/dictionary/?model_name=Lesson&obj_id={{ l.id }}");
					}
				});
				return false;
			});
			$('a.add_bookmark').click(function(){
				$.ajax({
					type: "GET",
					url: $(this).attr("href"),
					success: function(data){ $("#dialog_add_bookmarks").dialog(); }
				});
				return false;
			});
		});
	</script>
{% endblock%}